---
title: "CFA_passive_active"
author: "Sam Yu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(lavaan)
library(dplyr)
```

```{r}
# Prepare variables

active_items <- paste0("hope_", 1:4)
passive_items <- paste0("hope_", 5:7)
hopeless_items <- paste0("hopeless_", 1:2)

dat_cfa_anna <- dat_clean3 %>%
  select(all_of(c(active_items, passive_items, hopeless_items)))

# reverse coding hopeless
for (v in hopeless_items) {
  dat_cfa_anna[[paste0(v, "_r")]] <- 6 - dat_cfa_anna[[v]]
}

hopeless_rev_items <- paste0(hopeless_items, "_r")

```



```{r}
# CFA model comparison - define models

# Model 1:
# One-factor structure with hope
model_1 <- paste0(
  "Hope =~ ",
  paste(c(active_items, passive_items, hopeless_rev_items), collapse = " + ")
)

# Model 2:
# Two-factor: active hope + passive hope
# hopelessness reverse-coded as passive hope
model_2 <- paste0(
  "Active =~ ", paste(active_items, collapse = " + "), "\n",
  "Passive =~ ", paste(c(passive_items, hopeless_rev_items), collapse = " + ")
)

# Model 3:
# Two-factor: hope (active + passive) and hopelessness
model_3 <- paste0(
  "Hope =~ ", paste(c(active_items, passive_items), collapse = " + "), "\n",
  "Hopelessness =~ ", paste(hopeless_items, collapse = " + ")
)

# Model 4:
# Three-factor: active hope + passive hope + hopelessness
model_4 <- paste0(
  "Active =~ ", paste(active_items, collapse = " + "), "\n",
  "Passive =~ ", paste(passive_items, collapse = " + "), "\n",
  "Hopelessness =~ ", paste(hopeless_items, collapse = " + ")
)
```

```{r}
# CFA - model fit
fit_1 <- cfa(model_1, data = dat_cfa_anna, estimator = "MLR", missing = "fiml")
fit_2 <- cfa(model_2, data = dat_cfa_anna, estimator = "MLR", missing = "fiml")
fit_3 <- cfa(model_3, data = dat_cfa_anna, estimator = "MLR", missing = "fiml")
fit_4 <- cfa(model_4, data = dat_cfa_anna, estimator = "MLR", missing = "fiml")

# results
fit_1_result <- summary(fit_1, fit.measures = TRUE, standardized = TRUE)
fit_2_result <- summary(fit_2, fit.measures = TRUE, standardized = TRUE)
fit_3_result <- summary(fit_3, fit.measures = TRUE, standardized = TRUE)
fit_4_result <- summary(fit_4, fit.measures = TRUE, standardized = TRUE)

```

```{r}
# plausibility criteria check - function writing
check_plausibility <- function(fit) {
  pe <- parameterEstimates(fit, standardized = TRUE)
  
  # a & b: factor correlations
  factor_corr <- pe %>%
    filter(op == "~~", lhs != rhs) %>%
    filter(lhs %in% lavNames(fit, type = "lv"),
           rhs %in% lavNames(fit, type = "lv")) %>%
    select(lhs, rhs, est, std.all)
  
  corr_within_bounds <- all(factor_corr$std.all >= -1 & factor_corr$std.all <= 1, na.rm = TRUE)
  corr_below_070 <- all(abs(factor_corr$std.all) <= 0.7, na.rm = TRUE)
  
  # c: variances non-negative
  lv_var <- pe %>%
    filter(op == "~~", lhs == rhs, lhs %in% lavNames(fit, type = "lv")) %>%
    select(lhs, est, std.all)
  
  ov_var <- pe %>%
    filter(op == "~~", lhs == rhs, !(lhs %in% lavNames(fit, type = "lv"))) %>%
    select(lhs, est, std.all)
  
  non_negative_variance <- all(lv_var$est >= 0, na.rm = TRUE) &&
    all(ov_var$est >= 0, na.rm = TRUE)
  
  # d: standardized factor loading not under 0.4
  loadings <- pe %>%
    filter(op == "=~") %>%
    select(factor = lhs, item = rhs, est, std.all)
  
  loading_ok <- all(loadings$std.all >= 0.4, na.rm = TRUE)
  
  list(
    fit_measures = fitMeasures(fit, c("chisq", "df", "pvalue", "cfi", "tli", "rmsea", "srmr", "aic", "bic")),
    factor_correlations = factor_corr,
    latent_variances = lv_var,
    observed_variances = ov_var,
    loadings = loadings,
    criteria = data.frame(
      factor_corr_between_minus1_and_1 = corr_within_bounds,
      factor_corr_not_above_0_7 = corr_below_070,
      variances_non_negative = non_negative_variance,
      standardized_loadings_not_under_0_4 = loading_ok
    )
  )
}


```

```{r}
# check plausibility
res_1 <- check_plausibility(fit_1)
res_2 <- check_plausibility(fit_2)
res_3 <- check_plausibility(fit_3)
res_4 <- check_plausibility(fit_4)

# results overview
res_1$criteria
res_2$criteria
res_3$criteria
res_4$criteria

res_1$fit_measures
res_2$fit_measures
res_3$fit_measures
res_4$fit_measures

res_1$loadings
res_2$loadings
res_3$loadings
res_4$loadings

res_1$factor_correlations
res_2$factor_correlations
res_3$factor_correlations
res_4$factor_correlations


```

```{r}
# Removing items 5 & 6
active_items <- paste0("hope_", 1:4)
passive_items <- paste0("hope_", 7)
hopeless_items <- paste0("hopeless_", 1:2)

# Rerun the above analyses

```

```{r}
# EFA - preparation
library(psych)

efa_items <- dat_clean3 %>%
  select(c(
    paste0("hope_", 1:7),
    paste0("hopeless_", 1:2)
  ))

```

```{r}
# EFA - pre-analysis decision

KMO(efa_items)
cortest.bartlett(efa_items)

fa.parallel(efa_items, fa = "fa")
```

```{r}
# EFA - 4 factor
efa <- fa(efa_items, nfactors = 4, rotate = "oblimin")

print(efa$loadings, cutoff = 0.3)
```

