---
title: "Data_Cleaning"
author: "Sam Yu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
# Loading packages
#install.packages(c("tidyverse", "janitor", "skimr", "naniar"))
library(tidyverse)
library(janitor)
library(skimr)
library(naniar)
```

```{r}
# Data loading & formatting

raw <- read_csv("C:/Users/61457/Desktop/Masters/Internship/project/data/XR UK Survey Sam.csv",
                show_col_types = FALSE)
# clean names
dat <- raw %>% clean_names()

```

```{r}
dat <- dat %>%
  mutate(
    id_combo = if_else(
      !is.na(participant_id_1) & !is.na(participant_id_2) & !is.na(participant_id_3),
      paste(participant_id_1, participant_id_2, participant_id_3, sep = "_"),
      NA_character_
    )
  ) %>%
  group_by(id_combo) %>%
  filter(
    is.na(id_combo) |
      row_number() == which.max(progress)
  ) %>%
  ungroup() %>%
  select(-id_combo)

cat("Rows after removing duplicated participants:", nrow(dat), "\n")
```


```{r}
# removing people who do not give consent - output: dat_clean1

# number of participants not giving consent 
n_no_consent <- dat %>%
  filter(ethics != 1) %>% # 1 = consent, 0 = no consent
  nrow()

cat("Removed (no consent):", n_no_consent, "participants\n")

# number of participants who did not reply about withdrawing from the study 
# mainly due to incomplete 
# n_no_response <- dat %>% 
#   filter(ethics == 1 & is.na(project_description)) %>%
#   nrow()

# cat("Removed (no response at end):", n_no_response, "participants\n")

# number of participants who chose to withdrew their data
n_withdraw <- dat %>%
  filter(ethics == 1) %>%
  filter(project_description == 1) %>% 
  # 1 = withdraw data
  nrow()

cat("Removed (chose to withdraw):", n_withdraw, "participants\n")

# removal execution 

# sample size to start with
n_before <- nrow(dat)

# filter
# dat_clean1 <- dat %>%
#   filter(
#     !is.na(ethics) & !is.na(project_description) &
#     ethics != 0 & project_description != 1
#   )

dat_clean1 <- dat %>%
  filter(
    ethics == 1 & (is.na(project_description) | project_description != 1)
  )

# sample size after filtering
n_after <- nrow(dat_clean1)

# output: removed n 
cat("Removed (total):", n_before - n_after, "participants\n")
cat("Remaining:", n_after, "participants\n")

# quick look at where people drop out. 
ggplot(dat_clean1, aes(x = progress)) +
  geom_histogram(binwidth = 3, fill = "steelblue", color = "white") +
  scale_x_continuous(breaks = seq(0, 100, by = 3)) +
  labs(title = "Distribution of Progress", x = "Progress", y = "Count") +
  theme_minimal()


```

```{r}
#removing under 18  - output: dat_clean2

# sample size to start with
n_before <- nrow(dat_clean1)

# filter
dat_clean2 <- dat_clean1 %>%
  filter(is.na(project_description) | age >= 18)

# sample size after filtering
n_after <- nrow(dat_clean2)

# output: removed n 
cat("Removed (under 18):", n_before - n_after, "participants\n")
cat("Remaining:", n_after, "participants\n")

```
```{r}
# Setting all prefer not to say as na before applying exclusion criteria 

# treating these variables specially because prefer not to say is not 6

special_vars <- c(
  "permanent_shift",
  "gender",
  "region_country",
  "education",
  "employment",
  "income"
)

# replacing values with na. 
dat_clean2 <- dat_clean2 %>%
  mutate(
    across(everything(), ~ replace(., . %in% c(999, -9), NA)),
    # all values of 999 and -9 are prefer not to say. 
    across(
      -all_of(special_vars),
      ~ replace(., . == 6, NA)
      # apart from the special variables, 6 always means prefer not to say 
    ),
    permanent_shift = replace(permanent_shift, permanent_shift == 5, NA),
    gender = replace(gender, gender == 5, NA),
    region_country = replace(region_country, region_country == 14, NA),
    education = replace(education, education == 11, NA),
    employment = replace(employment, employment == 8, NA),
    income = replace(income, income == 7, NA)
  )

```


```{r}
# data quality: attention check  - output: dat_clean3

# sample size to start with
n_before <- nrow(dat_clean2)

# filter attention check == 3
dat_clean3 <- dat_clean2 %>%
  filter(attention_check == 3)

# sample size after filtering
n_after <- nrow(dat_clean3)

# output: removed n 
cat("Removed (failed attention check):", n_before - n_after, "participants\n")
cat("Remaining:", n_after, "participants\n")
```

```{r}
#removing non-activists
# define battery of testing
participation_bat <- c(
  paste0("past_participation_xr_", 1:7),
  paste0("participation_other_", 1:7)
)

# sample size to start with
n_before <- nrow(dat_clean3)

# Filter：non-activists
dat_clean4 <- dat_clean3 %>%
  rowwise() %>%
  filter(
    !all(c_across(all_of(participation_bat)) == 1, na.rm = TRUE)
    # 1 = Never
  ) %>%
  ungroup()

# sample size after filtering
n_after <- nrow(dat_clean4)

# output: removed n 
cat("Removed (no activity in past year):", n_before - n_after, "participants\n")
cat("Remaining:", n_after, "participants\n")
```

```{r}
# pre-registered rule: removing people with insufficient hope responses

# define batteries
hope_cog_bat <- c(paste0("hope_", 3:5))
hope_aff_bat <- c("hope_1", "hope_2", "hope_6", "hope_7")

# sample size to start with
n_before <- nrow(dat_clean4)

# Filter：cognitive ≥2 responses，affective ≥3 responses
dat_clean5 <- dat_clean4 %>%
  rowwise() %>%
  filter(
    sum(!is.na(c_across(all_of(hope_cog_bat)))) >= 2 &
    sum(!is.na(c_across(all_of(hope_aff_bat)))) >= 3
  ) %>%
  ungroup()

# sample size after filtering
n_after <- nrow(dat_clean5)

# output: removed n 
cat("Removed (insufficient hope responses):", n_before - n_after, "participants\n")
cat("Remaining:", n_after, "participants\n")
```

```{r}
# pre-registered rule: removing people with insufficient action intention responses

# define battery
action_bat <- paste0("action_intentions_", 1:15)

# sample size to start with
n_before <- nrow(dat_clean5)

# Filter: at least 11 responses
dat_clean6 <- dat_clean5 %>%
  rowwise() %>%
  filter(
    sum(!is.na(c_across(all_of(action_bat)))) >= 11
  ) %>%
  ungroup()

# sample size after filtering
n_after <- nrow(dat_clean6)

# output: removed n 
cat("Removed (insufficient action intention responses):", n_before - n_after, "participants\n")
cat("Remaining:", n_after, "participants\n")

```


```{r}
# data quality: straight lining

# define test batteries 
emotion_bat <- c(
  paste0("anger_", 1:3),
  paste0("fear_", 1:3),
  paste0("joy_", 1:3),
  paste0("hope_", 1:7),
  paste0("hopeless_", 1:2),
  paste0("emotions_xr_", 1:4)
)

action_bat <- paste0("action_intentions_", 1:15)

# function：calculate 80% same answer
prop_max_same <- function(x) {
  x <- x[!is.na(x)]
  if(length(x) == 0) return(NA)
  max(table(x)) / length(x)
}

# sample size to start with
n_before <- nrow(dat_clean6)

# labeling same answer percentage
dat_clean6 <- dat_clean6 %>%
  rowwise() %>%
  mutate(
    emotion_max = prop_max_same(c_across(all_of(emotion_bat))),
    action_max  = prop_max_same(c_across(all_of(action_bat)))
  ) %>%
  ungroup()

# Disentangle the two type
n_action_sl <- dat_clean6 %>%
  filter(action_max >= 0.8) %>%
  nrow()

n_emotion_sl <- dat_clean6 %>%
  filter(emotion_max >= 0.8) %>%
  nrow()

# Filtering according to same answer percentage
dat_clean7 <- dat_clean6 %>%
  filter(
    (emotion_max < 0.8) & (action_max < 0.8)
  )

# sample size after filtering
n_after <- nrow(dat_clean7)

# output: removed n 
cat("Removed (emotion straightlining):", n_emotion_sl, "\n")
cat("Removed (action straightlining):", n_action_sl, "\n")
cat("Total removed (straightlining ≥80%):", n_before - n_after, "\n")
cat("Remaining:", n_after, "\n")

```


```{r}
# Removing people who completed the survey extremely fast

# sample size to start with
n_before <- nrow(dat_clean7)

# calculate mean and SD 
mean_time <- mean(dat_clean7$duration_in_seconds, na.rm = TRUE)
sd_time_full <- sd(dat_clean7$duration_in_seconds, na.rm = TRUE)

# identify outliers
time_for_calc <- dat_clean7$duration_in_seconds[
  dat_clean7$duration_in_seconds >= (mean_time - 3 * sd_time_full) &
  dat_clean7$duration_in_seconds <= (mean_time + 3 * sd_time_full)
]

# exclude outliers for threshol calculation
median_time <- median(time_for_calc, na.rm = TRUE)
sd_time <- sd(time_for_calc, na.rm = TRUE)
cutoff <- median_time - 2 * sd_time

# Filter (on all data)
dat_clean8 <- dat_clean7 %>%
  filter(!is.na(duration_in_seconds) & duration_in_seconds >= cutoff)

# sample size after filtering
n_after <- nrow(dat_clean8)

# output
cat("Removed (too fast responses):", n_before - n_after, "participants\n")
cat("Remaining:", n_after, "participants\n")
```
```{r}
#write.csv(dat_clean8, "dat_clean8.csv", row.names = FALSE)
```

