---
title: "Descriptive Data"
author: "Sam Yu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(psych)      # descriptives + omega
library(naniar)     # missing
library(ggplot2)
library(corrplot)
library(reshape2)
library(dplyr)
library(purrr)
library(naniar)
```


```{r}
# hope items 
# hope items
hope_items <- dat_clean8 %>%
  select(starts_with("hope_"))

describe(hope_items)

# hope response distribution 
library(tidyverse)

# long format
hope_long <- hope_items %>%
  pivot_longer(everything(), names_to = "item", values_to = "value")

# labelling - numbering
hope_long <- hope_long %>%
  mutate(value = factor(value,
                        levels = c(1,2,3,4,5),
                        labels = c("Strongly disagree",
                                   "Disagree",
                                   "Neutral",
                                   "Agree",
                                   "Strongly agree")))

# proportion of each response
plot_data <- hope_long %>%
  group_by(item, value) %>%
  summarise(n = n(), .groups = "drop") %>%
  group_by(item) %>%
  mutate(prop = n / sum(n))

# plotting
ggplot(plot_data, aes(x = item, y = prop, fill = value)) +
  geom_col(position = "fill", width = 0.7) +
  coord_flip() +
  scale_fill_manual(values = c(
    "Strongly disagree" = "#d73027",
    "Disagree" = "#fc8d59",
    "Neutral" = "#fee090",
    "Agree" = "#91bfdb",
    "Strongly agree" = "#4575b4"
  )) +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  labs(x = NULL, y = "Percentage", fill = NULL)

```

```{r}
# all other variables, composite score 

dat_desc <- dat_clean8 %>%
  mutate(
    intention = rowMeans(select(., starts_with("action_intentions_")), na.rm = TRUE),
    env_concern = rowMeans(select(., starts_with("env_concerns_")), na.rm = TRUE),
    social_id = rowMeans(select(., starts_with("social_identification_")), na.rm = TRUE),
    anger = rowMeans(select(., starts_with("anger_")), na.rm = TRUE),
    fear = rowMeans(select(., starts_with("fear_")), na.rm = TRUE),
    joy = rowMeans(select(., starts_with("joy_")), na.rm = TRUE),
    hopeless = rowMeans(select(., starts_with("hopeless_")), na.rm = TRUE),
    injustice = rowMeans(select(., starts_with("climate_injustice_")), na.rm = TRUE),
    moral = rowMeans(select(., starts_with("moral_obligation_")), na.rm = TRUE),
    collective_efficacy = rowMeans(select(., starts_with("collective_efficacy_")), na.rm = TRUE),
    self_efficacy = self_efficacy   
  )

# non-hope variable descriptive
composites <- dat_desc %>%
  select(intention, env_concern, social_id, anger, fear, joy,
         hopeless, injustice, moral, collective_efficacy, self_efficacy)

describe(composites)
```

```{r}
# missing per variable - visualisation
gg_miss_var(select(dat_clean8, starts_with("hope_")))
gg_miss_var(select(dat_clean8, starts_with("action_intentions_")))
gg_miss_var(select(dat_clean8, starts_with("social_identification_")))
gg_miss_var(select(dat_clean8, starts_with("anger_")))
gg_miss_var(select(dat_clean8, starts_with("fear_")))  
# non random missing? 
gg_miss_var(select(dat_clean8, starts_with("joy_")))   
# non random missing? 
gg_miss_var(select(dat_clean8, starts_with("hopeless_")))
gg_miss_var(select(dat_clean8, starts_with("climate_injustice_")))
gg_miss_var(select(dat_clean8, starts_with("moral_obligation_")))
gg_miss_var(select(dat_clean8, starts_with("collective_efficacy_")))
gg_miss_var(select(dat_clean8, self_efficacy))


# mcar_test(select(dat_clean8, starts_with("hope_")))
# mcar_test(select(dat_clean8, starts_with("action_intentions_")))
# mcar_test(select(dat_clean8, starts_with("social_identification_")))
# mcar_test(select(dat_clean8, starts_with("anger_")))
# mcar_test(select(dat_clean8, starts_with("fear_")))
# mcar_test(select(dat_clean8, starts_with("joy_"))) 
# mcar_test(select(dat_clean8, starts_with("hopeless_")))
# mcar_test(select(dat_clean8, starts_with("climate_injustice_")))
# mcar_test(select(dat_clean8, starts_with("moral_obligation_")))
# mcar_test(select(dat_clean8, starts_with("collective_efficacy_")))


# missing data test
scales <- list(
  hope = dat_clean8 %>% select(starts_with("hope_")),
  action_intention = dat_clean8 %>% select(starts_with("action_intentions_")),
  social_identification = dat_clean8 %>% select(starts_with("social_identification_")),
  anger = dat_clean8 %>% select(starts_with("anger_")),
  fear = dat_clean8 %>% select(starts_with("fear_")),
  joy = dat_clean8 %>% select(starts_with("joy_")),
  hopeless = dat_clean8 %>% select(starts_with("hopeless_")),
  climate_injustice = dat_clean8 %>% select(starts_with("climate_injustice_")),
  moral_obligation = dat_clean8 %>% select(starts_with("moral_obligation_")),
  collective_efficacy = dat_clean8 %>% select(starts_with("collective_efficacy_"))
  #self_efficacy = dat_clean8 %>% select(self_efficacy)
)


mcar_results <- imap_dfr(scales, ~{
  res <- mcar_test(.x)
  tibble(
    scale = .y,
    statistic = res$statistic,
    df = res$df,
    p_value = res$p.value
  )
})

mcar_results



```

```{r}
# correlation matrix - Hope items
cor_matrix <- cor(hope_items, use = "pairwise.complete.obs")
cor_matrix[upper.tri(cor_matrix)] <- NA
cor_matrix

cor_long <- melt(cor_matrix, na.rm = TRUE)

ggplot(cor_long, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(value, 2))) +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  theme_minimal() +
  labs(title = "Correlation Matrix of Hope Items")

```

```{r}
library(tidyverse)
library(reshape2)

# correlation
hope_items <- dat_clean8 %>%
  select(starts_with("hope_"))

composites <- dat_desc %>%
  select(intention, env_concern, social_id, anger, fear, joy,
         hopeless, injustice, moral, collective_efficacy, self_efficacy)

# r matrix
cor_matrix <- cor(hope_items, composites, use = "pairwise.complete.obs")

# p matrix
p_matrix <- matrix(NA, nrow = ncol(hope_items), ncol = ncol(composites))
rownames(p_matrix) <- colnames(hope_items)
colnames(p_matrix) <- colnames(composites)

for (i in 1:ncol(hope_items)) {
  for (j in 1:ncol(composites)) {
    p_matrix[i, j] <- cor.test(
      hope_items[[i]],
      composites[[j]],
      use = "pairwise.complete.obs"
    )$p.value
  }
}

# melt
cor_long <- melt(cor_matrix, varnames = c("Hope", "Composite"), value.name = "r")
p_long   <- melt(p_matrix, varnames = c("Hope", "Composite"), value.name = "p")

plot_df <- left_join(cor_long, p_long, by = c("Hope", "Composite")) %>%
  mutate(
    sig = case_when(
      p < .001 ~ "***",
      p < .01  ~ "**",
      p < .05  ~ "*",
      TRUE     ~ ""
    ),
    label = paste0(round(r, 2), sig)
  )

ggplot(plot_df, aes(x = Composite, y = Hope, fill = r)) +
  geom_tile(color = "white") +
  geom_text(aes(label = label), size = 3) +
  scale_fill_gradient2(
    low = "blue",
    mid = "pink",
    high = "red",
    midpoint = 0
  ) +
  theme_minimal() +
  labs(x = "Composite Variables", y = "Hope Items", fill = "r") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```



