---
title: "EFA"
author: "Sam Yu"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}

library(psych)


dat_clean <- readRDS("../data/dat_clean.rds")

hope_items <- dat_clean %>%
  select(paste0("hope_", 1:7))

```

```{r}
# test for FA suitability 

KMO(hope_items)
# determine the suitability of data for factor analysis by measuring the sampling suitability
# result: acceptable as FA - mediocre 

cortest.bartlett(hope_items)
# evaluates whether a correlation matrix differs significantly from an identity matrix, 
# confirming if variables are sufficiently related to justify factor analysis
# result: yes, the data is suitable for reduction
```

```{r}
# Determining the number of factors. 
# parallel testing method
fa.parallel(hope_items, fa = "fa", plot=TRUE, error.bars=TRUE, se.bars=TRUE)

# Minimum Average Partial and Very Simple Structure method
VSS_result <- VSS(hope_items, n = 5, rotate = "oblimin")
VSS_result
```



```{r}
# EFA models
#efa1 <- fa(hope_items, nfactors = 1, rotate = "oblimin", fm = "ml")
#efa2 <- fa(hope_items, nfactors = 2, rotate = "oblimin", fm = "ml")
efa3 <- fa(hope_items, nfactors = 3, rotate = "oblimin", fm = "ml")

# fit_compare <- data.frame(
#   factors = c(1, 3),
#   TLI = c(efa1$TLI, efa3$TLI),
#   RMSEA = c(efa1$RMSEA[1], efa3$RMSEA[1]),
#   RMSR = c(efa1$rms, efa3$rms),
#   BIC = c(efa1$BIC, efa3$BIC)
# )
# 
# fit_compare

# Compare loadings
#print(efa1$loadings, cutoff = .40)
#print(efa2$loadings, cutoff = .40)
print(efa3$loadings, cutoff = .30)

# Factor correlations
#efa2$Phi
efa3$Phi

# saving as csv
efa_loading_table <- as.data.frame(unclass(efa3$loadings))
efa_loading_table <- round(efa_loading_table, 3)

efa_loading_table$item <- rownames(efa_loading_table)

efa_loading_table <- efa_loading_table %>%
  select(item, everything())

write.csv(
  efa_loading_table,
  "efa_loading_table.csv",
  row.names = FALSE
)

```

```{r}
# consistency 
f1 <- hope_items[, paste0("hope_", 1:4)]
f2 <- hope_items[, c("hope_3", "hope_7")]

omega(hope_items)


```

